# Generated by Django 3.1.3 on 2020-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201123_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
