# Generated by Django 3.1.3 on 2020-11-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/logo.jpg', null=True, upload_to=''),
        ),
    ]
